/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.net.*;
import java.io.*;

public class MainATM {





    public static void main(String[] args) throws IOException {
        System.out.println("Arguments 0 - " + args[0]);

    }
}
