/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.net.*;
import java.io.*;

public class MainBank {

    private ServerSocket ss;
    private Socket s;
    private ObjectOutputStream opt;
    private ObjectInputStream ipt;

    public MainBank(){

    }

    public void startRunning(){
        try{
            ss = new ServerSocket(3000);
            while (true) {
                try{
                    waitForConnection();
                    setupStreams();
                    communication();
                }catch (EOFException e){
                    System.out.println("\nServer: Lost Connection. ");
                }finally {
                    closeConnection();
                }
            }
        }catch(IOException e){
            e.printStackTrace();
        }
    }

    private void waitForConnection() throws IOException{
        System.out.println("Listening...\n");
        s = ss.accept();
        System.out.println("Connection.\n");
    }

    private void setupStreams() throws IOException{
        opt = new ObjectOutputStream(s.getOutputStream());
        opt.flush();

        ipt = new ObjectInputStream(s.getInputStream());
        System.out.println("\nStreams now setup. \n");
    }

    private void communication() throws IOException{
        String msg = "hi";
        sendSimpleMessage(msg);
        do{
            try{
                msg = (String) ipt.readObject();
            }catch(ClassNotFoundException e){
                System.out.println("\nError.");
            }
        }while(!msg.equals("ATM: END"));
    }

    private void closeConnection() {
        System.out.println("\nClosing Connection...");
        try{
            opt.close();
            ipt.close();
            s.close();

        }catch (IOException e){
            e.printStackTrace();
        }
    }

    private void sendSimpleMessage(String msg){
        try{
            opt.writeObject("MainBank:  " + msg);
            opt.flush();
        }catch (IOException e){
            System.out.println("\n Unable to send message.");
        }
    }

    public static void main(String[] args) throws IOException {
        System.out.println("Arguments 0 - " + args[0]);

        MainBank mb = new MainBank();
        mb.startRunning();
    }

}
