/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class MainBank {

    public static void main(String[] args) {
        System.out.println("Arguments 0 - " + args[0]);
    }
}
